### ISSUE TITLE
It's been two months since you promised

### ISSUE THREAD

**Issue by a2821952** [MarkFzp/Deep-Whole-Body-Control#3]
You mentioned in your last response that the project would be officially open-sourced in February. However, it is now May, and after such a long wait, I have become pessimistic about whether the project will actually be open-sourced. I hope not to make promises about open-sourcing when the timeline is uncertain, as it is misleading for reviewers and readers.

**Comment by MarkFzp** [comment]
Thanks for your interests in this project! I mentioned in our last communication that "**I'll try my best** to open source it within this Feb" as the exact timeline depends on my other ongoing projects. I made the promise about open-sourcing as I will! And the promise about the open sourcing is only targeted towards the community only because I personally think it's good to open source. This is not a norm in the robotics community, as open sourcing much more complicated than other AI domains. **And I never mentioned anything about open sourcing in my paper (to readers) or on OpenReview (to reviewers). The link to this repo on the project website was only included after this paper got accepted to CoRL 2022. Please do not make unfounded claims.** Thanks 

The updated timeline will be the week after June 8th.

**Comment by a2821952** [comment]
Thank you very much for your reply. I'm sorry if what I said upset you. I am truly looking forward to the open-sourcing of this project and really appreciate the value of your work. I have just had many encounters with so-called "open source" projects. 
I understand your current situation and hope your submission goes smoothly. I am eagerly anticipating the project's open-sourcing.
